### PR TITLE
Add install instructions for Linux and adapt the instructions for Windows.

### PR DESCRIPTION
**Pull request by asynts**
This is essentially #28 but I renamed the branch from `asynts/linux-instructions` to `asynts/instructions`. I don't know if it's possible to rename a branch while a pull request is open, and didn't want to try it out in a live environment.

It would be really helpful if someone independently tested the instructions.

### CODE REVIEW

**Comment by jflopezfernandez** [comment]
I just tested the setup instructions and was able to successfully run the WebUI application.

`uname -a` output for my test environment: `Linux d1 4.19.98-1-MANJARO #1 SMP Thu Jan 23 10:34:28 UTC 2020 x86_64 GNU/Linux`

**Comment by asynts** [comment]
@jflopezfernandez Thanks! Actually the `uname -a` thing is a pretty good idea, here is mine:

~~~none
$ uname -a
Linux y 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux
~~~

**Review by ArtOfCode- — APPROVED** [review]

**Comment by ranolfi** [comment]
Got it running here too. `Linux rlinux 5.4.15-1-ck-piledriver #1 SMP PREEMPT Sun, 26 Jan 2020 12:55:07 +0000 x86_64 GNU/Linux`.

Note, the [`dotnet-sdk`](https://www.archlinux.org/packages/community/x86_64/dotnet-sdk/) package does not pull [`aspnet-runtime`](https://www.archlinux.org/packages/community/x86_64/aspnet-runtime/) which is also a dependency for this project. This was brought to my attention by contributor _mcalex_ on Discord. I'm approving this PR, but holding off merging in case you want to take the opportunity to add a note for that in the instructions. Otherwise just let me know and I'll go ahead and merge. Thanks!

**Review by ranolfi — APPROVED** [review]

**Comment by mcalexster** [comment]
I couldn't follow the instructions as I use Arch linux and the MS download link doesn't include that distro.  I created a branch and issue to add arch specific instructions (as per @ranolfi's comment above. Is it more appropriate to create a new PR or merge with this?  (ie: Should I just copy the readme.md here, or push the branch?)

**Comment by asynts** [comment]
@mcalexster I added a commit that adds a note a few seconds before you commented. Does that suffice?

**Comment by mcalexster** [comment]
@asynts  Cool.  I'll delete/close the issue

**Comment by asynts** [comment]
What I just noticed when reading through #52 is that I at some point dropped `dotnet ef database update` from the instructions. I've never run that on my machine and everything seems to work?

Does this happen when `ApplicationDbContext.Database.Migrate` [is called][1]? When reading [this article][2] it seems like this is the case. That would mean that `dotnet-ef` wouldn't have to be installed.

  [1]: https://github.com/codidact/core/blob/2532a8ec6ba9bdcd8975cd15e697e7156b91027c/src/WebUI/Startup.cs#L73
  [2]: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#update-the-database

**Comment by cellio** [comment]
What is blocking the merge of this PR?

**Comment by asynts** [comment]
This pull request could be merged in my opinion.

https://discordapp.com/channels/634104110131445811/635510829499940912/688836123421835340

**Pull request merged**
