### PR TITLE
Add project information to README

### PR DESCRIPTION
**Pull request by ozewski**
Add project information to README.

### CODE REVIEW

**Review by ranolfi — CHANGES_REQUESTED** [review]
Please ammend this commit with a proper commit message - We already got a couple "update README.md" commits and these are not useful.

Just write a short summary specifying *what* was changed :) refer to: https://github.com/codidact/core/wiki/Committing-guidelines

**Comment by ArtOfCode-** [comment]
@ozewski that's the issue title you changed there - it's the _commit_ that needs a full message. Locally, you want these commands, assuming you've made no changes since doing this:

```
git add README.md
git commit --amend -m "DESCRIBE COMMIT HERE"
```

**Comment by ozewski** [comment]
@ArtOfCode- D'oh! This is what happens when you do stuff at all hours of the night. I'll make another PR later since I messed up stuff with this one.

**Comment by alerque** [comment]
@ozewski You don't need to open new PR's to fix issues, git allows you to fix up the history and the PR will update to whatever you push here. You're stuck now that you've deleted the branch, but next time know that you don't have to (and probably shouldn't) close and re-open PRs to fix commits in them.

**Comment by ranolfi** [comment]
@alerque I actually believe that @ozewski can restore the branch from this page. Once done, the PR can be reopened.

**Pull request closed without merging**
