### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by LionelBergen**
Remade: https://github.com/codidact/core/pull/54 With better commit messages

Added `dotnet-format`
Ran `dotnet-format` (a few minor whitespace changes)
Added a default `.editorconfig`

Relates to: #26

~Notes:
There is no way to check for violations without automatically fixing them using this tool.
For example, we may want to run a check and fail before tests are run, or before a deploy. Rather than asking contributors to run it before/after a merge request.~

### CODE REVIEW

**Comment by LionelBergen** [comment]
I found it easier to remake the branch than to edit the commit so I made a new pull request for it

**Comment by ranolfi** [comment]
Sounds good, thanks. We'll checkout and test, merging if it works as intended.

Note: commit eb1ca1e9 will need to conform to [committing guidelines](https://github.com/codidact/core/wiki/Committing-guidelines) (subject line too long). Recommend amend and force-push.

The "taken from (...)" bit should be in the commit body.

**Review by ArtOfCode- — APPROVED** [review]

**Comment by LionelBergen** [comment]
@ranolfi commit message has been updated

**Comment by misha130** [comment]
Could you please add the editorconfig file to the .sln file for those who use Visual Studio and not vscode?
Like so:
``` 
ProjectSection(SolutionItems) = preProject
        .editorconfig = .editorconfig
        CONTRIBUTING.md = CONTRIBUTING.md
        README.md = README.md
    EndProjectSection
 ```

**Comment by ranolfi** [comment]
> There is no way to check for violations without automatically fixing them using this tool.
> For example, we may want to run a check and fail before tests are run, or before a deploy. Rather than asking contributors to run it before/after a merge request.

Btw checking for violations is as simple as increasing the severity in `.editorconfig` afaik. (I used severity=`warning` for most of [my rules](https://github.com/codidact/core/blob/ranolfi/skeleton/Solution/.editorconfig), and `error` for a few). It shows up in the error window without even building the project, even though in my opinion a successful build should be a requirement for submitting a PR.

**Comment by LionelBergen** [comment]
@ranolfi I agree successful builds should be a requirement, but I find it surprising or may not notice if the build automatically fixes all the issues.

I'd rather the build tell me I have issues and force me to run the auto-fix

**Comment by ranolfi** [comment]
> @ranolfi I agree successful builds should be a requirement, but I find it surprising or may not notice if the build automatically fixes all the issues.
> 
> I'd rather the build tell me I have issues and force me to run the auto-fix

Yep, me too. But at least in Visual Studio, the build fails instead of auto-fixing, so I get the desired behavior by default :)

**Comment by LionelBergen** [comment]
> > @ranolfi I agree successful builds should be a requirement, but I find it surprising or may not notice if the build automatically fixes all the issues.
> > I'd rather the build tell me I have issues and force me to run the auto-fix
> 
> Yep, me too. But at least in Visual Studio, the build fails instead of auto-fixing, so I get the desired behavior by default :)

Oh okay good. I only tested using command line and it seems to auto-correct, even when using the `--check` argument

**Comment by LionelBergen** [comment]
@misha130 I've updated my branch to have .editorconfig inside the .sln file

**Comment by cellio** [comment]
This has been sitting for a while with no new activity and one approval.  What needs to happen for it to merge?

**Review by asynts — APPROVED** [review]
This pull request could be merged in my opinion.

https://discordapp.com/channels/634104110131445811/635510829499940912/688845823810994229

**Comment by Daksh14** [comment]
@LionelBergen hello! Please stick to our [commit guidelines](https://github.com/codidact/core/wiki/Committing-guidelines) before committing. Everything else looks fine here

**Pull request merged**
